mysite/mysite/urls.py
from django.conf.urls import include,url
from django.contrib import admin
admin.autodiscover()


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^wowCS/', include('wowCS.urls')),
    url(r'^', include('wowCS.urls')),
]

mysite/wowCS/urls.py
from django.conf.urls import url
from . import views

app_name = 'wowCS'

urlpatterns = [
    # main page of the root
    url(r'^$',views.IndexView.as_view(),name = 'index'),
    # login
    url(r'^login/$',views.log_in,name = 'login'),
    # logout
    url(r'^logout/$', views.log_out, name='logout'),
    # register
    url(r'^register/$',views.UserFormView.as_view(),name = 'register'),
    # profile
    url(r'^profile/$',views.profile,name = 'profile'),
    # /allnote/
    url(r'^allnote/$',views.AllNotesView.as_view(), name = 'show_all_notes'),
    # /allnote/
    url(r'^allnotebook/$', views.AllNotebooksView.as_view(), name='show_all_notebooks'),

    # /notebook/Python/
    url(r'^notebook/(?P<notebook_title>[a-zA-Z0-9]+)/$',views.NoteBookView.as_view(), name = 'catalogue'),
    # /note/1/
    url(r'^note/(?P<note_id>[0-9]+)/$',views.detail, name = 'detail'),


    # # /add_notebook/
    url(r'add/notebook/$', views.create_notebook, name='notebook-add'),
    # /update/notebook/Python/
    url(r'update/notebook/(?P<notebook_title>[a-zA-Z0-9]+)/$', views.update_notebook, name='notebook-update'),
    # /delete/notebook/Python/
    url(r'delete/notebook/(?P<notebook_title>[a-zA-Z0-9]+)/$', views.delete_notebook, name='notebook-delete'),

    # /Python/add/
    url(r'add/note/$', views.create_note, name='note-add'),
    # /update/note/1/
    url(r'update/note/(?P<note_id>[0-9]+)/$', views.update_note, name='note-update'),
    # /delete/note/1/
    url(r'delete/note/(?P<note_id>[0-9]+)/$', views.delete_note, name='note-delete'),

    # /favorite/1
    url(r'^favorite/(?P<note_id>[0-9]+)/$',views.favorite, name = 'add-favorite'),

    # /favorite/all
    url(r'^favorite/all/$',views.FavoriteView.as_view(), name = 'allfavorite'),

    # /see/1
    # public profile page for user 1.
    url(r'^see/(?P<user_id>[0-9]+)/$',views.UserView.as_view(), name = 'see'),

    url(r'^search/$', views.SearchView.as_view(), name='search'),

    # api

    # method : get
    url(r'^api/10recentnotes/$', views.RecentNoteList.as_view(), name='10recentnotes'),
    # method : get
    url(r'^api/10recentnotebooks/$',views.RecentNotebookList.as_view(),name='10recentnotebooks'),

    url(r'^api/10popular/$',views.Popular.as_view(),name='popular'),

    url(r'^api/preview/(?P<id>[0-9]+)/$',views.Preview.as_view(),name='preview'),

    url(r'^api/usercatagory/$',views.UserCatagory.as_view(),name="usercatagory"),

    url(r'^api/notesin/(?P<notebook_title>[a-zA-Z0-9]+)/$', views.NotebookCatagory.as_view(), name="notesin"),

]

mysite/wowCS/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import Permission, User
from datetime import datetime

# Create your models here.
class Notebook(models.Model):
    user = models.ForeignKey(User, default=1)
    notebook_title = models.CharField(max_length=500)
    notebook_description = models.CharField(max_length=250,null=True)


    class Meta:
        unique_together = ('user', 'notebook_title',)

    def get_absolute_url(self):
        return reverse('wowCS:index')

    def __str__(self):
        return self.notebook_title


class Note(models.Model):
    notebook = models.ForeignKey(Notebook,on_delete= models.CASCADE,null=True,blank=True)
    user = models.ForeignKey(User, default=1)
    note_title = models.CharField(max_length=200)
    note_content = models.TextField()
    # public/private status
    ispublic = models.BooleanField(default=True)
    # the count of marked as favorite.
    favorite_count = models.IntegerField(default=0)
    date = models.DateTimeField(default=datetime.now, blank=True)
    def get_absolute_url(self):
        return reverse('wowCS:catalogue',kwargs={'notebook_title':self.notebook})

    def __str__(self):
        return self.note_title


class Favorite(models.Model):
    user = models.ForeignKey(User, default=1)
    favorite_id = models.IntegerField()

    class Meta:
        unique_together = ('user', 'favorite_id',)

mysite/wowCS/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Notebook,Note
from pagedown.widgets import PagedownWidget



class NoteBookForm(forms.ModelForm):
	

	class Meta:
		model = Notebook
		fields = ('notebook_title','notebook_description')


class NoteForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
			user = kwargs.pop('user', None)
			super(NoteForm, self).__init__(*args, **kwargs)
			if user:
				self.fields['notebook'].queryset = Notebook.objects.filter(user = user)

	note_content = forms.CharField(widget=PagedownWidget())
	class Meta:
		model = Note
		fields = ['notebook','note_title','note_content','ispublic']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username','email','password']

mysite/wowCS/views.py
from django.views import generic
from django.urls import reverse
from .models import Notebook,Note,Favorite,User
from django.shortcuts import render,redirect, get_object_or_404
from django.http import HttpResponseRedirect,HttpResponseForbidden
from django.contrib.auth import authenticate,login,logout
from django.views.generic import View
from .forms import UserForm,NoteBookForm,NoteForm
from .serializers import NoteSerializer,NoteBookSerializer
from rest_framework.views import APIView
from rest_framework.response import Response
import pypandoc
import re
from datetime import datetime



# index view
class IndexView(generic.ListView):

    template_name = 'wowCS/index.html'
    context_object_name = 'all_note'

    def get_queryset(self):
        return Note.objects.filter(ispublic=True)

    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        context = self.get_context_data()
        if request.user.is_authenticated():
            context['islogin'] = True
        else:
            context['islogin'] = False
        return self.render_to_response(context)

# catalogue view for given notebook_title
class NoteBookView(generic.ListView):
    template_name = 'wowCS/catalogue.html'
    context_object_name = 'notebook'

    def get_queryset(self):
        notebook = Notebook.objects.get(notebook_title=self.kwargs.get('notebook_title'),user=self.request.user)
        # if the requested notebook doesn't belong to the current user, then return None
        if notebook.user==self.request.user:
            return notebook
        else:
            return None

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            return render(request, 'wowCS/login.html')
        else:
            self.object_list = self.get_queryset()
            #if the get_queryset() returned None, then redirect to the wrong.html
            if not self.object_list:
                return render(request,'wowCS/wrong.html',{'error_message':"<h1>You can't see that notebook!</h1>"})
            context = self.get_context_data()
            return self.render_to_response(context)

# all notes view for listing all notes.
class AllNotebooksView(generic.ListView):
    template_name = 'wowCS/show_all_notebooks.html'
    context_object_name = 'all_notebooks'

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            return render(request, 'wowCS/login.html')
        else:
            self.object_list = self.get_queryset()
            context = self.get_context_data()
            return self.render_to_response(context)

    def get_queryset(self):
        return Notebook.objects.filter(user=self.request.user)

# all notes view for listing all notes.
class AllNotesView(generic.ListView):
    template_name = 'wowCS/show_all_notes.html'
    context_object_name = 'all_notes'

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            return render(request, 'wowCS/login.html')
        else:
            self.object_list = self.get_queryset()
            context = self.get_context_data()
            context['header_text'] = "All my notes"
            return self.render_to_response(context)

    def get_queryset(self):
        notes= []
        for notebook in Notebook.objects.filter(user=self.request.user):
            for note in notebook.note_set.all():
                notes.append(note.pk)
        return Note.objects.filter(pk__in=notes)

#detail view for the detail of a note
def detail(request,note_id):
    # if not request.user.is_authenticated():
    #     return render(request, 'wowCS/login.html')
    login_status = request.user.is_authenticated()
    note = Note.objects.get(id=note_id)
    if note.ispublic:
        html = pypandoc.convert_text(note.note_content, 'html', format='md')
        context = {'note': note, 'note_content': html, 'islogin': login_status}
        if login_status:
            if int(note_id) in [int(f.favorite_id) for f in Favorite.objects.filter(user=request.user)]:
                context['is_favorite'] = True
        return render(request, 'wowCS/detail.html',context )
    # show the private detail only if the requested note belongs to the current user
    if not login_status:
        return render(request, 'wowCS/wrong.html', {'islogin':False,'error_message': "<h1>You have to login before seeing this private note.</h1>"})
    if note.user==request.user:
        html = pypandoc.convert_text(note.note_content, 'html',format='md')
        return render(request, 'wowCS/detail.html', {'note': note,'note_content':html})
    else:
        return render(request, 'wowCS/wrong.html', {'islogin':True,'error_message': "<h1>You can't see that note!</h1>"})


# functions and class for login/logout/register/profile
def log_in(request):
    if request.user.is_authenticated():
        return render(request, 'wowCS/index.html')
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            return render(request, 'wowCS/login.html', {'islogin':False,'error_message': 'Invalid login'})
    return render(request, 'wowCS/login.html')

def log_out(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'wowCS/login.html', context)

class UserFormView(View):
    form_class = UserForm
    template_name = 'wowCS/registration_form.html'

    # display a blank form
    def get(self,request):
        form = self.form_class(None)
        return render(request,self.template_name,{'form':form})


    # process form data
    def post(self,request):
        form = self.form_class(request.POST)
        if form.is_valid():
            # create an object from the form data but not saved.
            user = form.save(commit=False)

            # cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user.set_password(password)
            user.save()

            # Generate a default empty notebook for user.
            defaultNB = Notebook()
            defaultNB.notebook_title = 'default'
            defaultNB.user = user
            defaultNB.genre = 'blank'
            defaultNB.notebook_description = 'Default Notebook.'
            defaultNB.save()

            # Generate a introduction note for new user.

            # returns User objects if credentials are correct
            user = authenticate(username = username,password=password)
            if user is not None and user.is_active:
                login(request,user)
                return redirect('wowCS:index')
                # request.user.username/profile...
        else:
            return render(request, self.template_name, {'form': form})

def profile(request):
    if not request.user.is_authenticated():
        return render(request, 'wowCS/login.html')



    return render(request,'wowCS/profile.html',{'user':request.user})

class UserView(generic.ListView):
    template_name = 'wowCS/show_all_notes.html'
    context_object_name = 'all_notes'

    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        context = self.get_context_data()
        context['header_text'] = "All notes from this user"
        return self.render_to_response(context)

    def get_queryset(self):
        notes= []
        target = User.objects.get(id=self.kwargs.get('user_id'))
        for notebook in Notebook.objects.filter(user=target):
            for note in notebook.note_set.all():
                if note.ispublic:
                    notes.append(note.pk)
        return Note.objects.filter(pk__in=notes)





# create/update/delete/ notebook
def create_notebook(request):
    if not request.user.is_authenticated():
        return render(request, 'wowCS/login.html')
    else:
        form = NoteBookForm(request.POST or None, request.FILES or None)
        if form.is_valid():

            notebook = form.save(commit=False)
            if not re.match('^[a-zA-Z0-9]+$',notebook.notebook_title):
                context = {"form": form,'error_message':"Illegal Notebook name!"}
                return render(request, 'wowCS/create_notebook.html', context)
            notebook.user = request.user
            try:
                notebook.save()
            except:
                context = {"form": form,'error_message':"Duplicate Notebook name!"}
                return render(request, 'wowCS/create_notebook.html', context)
            return HttpResponseRedirect(notebook.get_absolute_url())
        context = {
            "form": form,
        }
        return render(request, 'wowCS/create_notebook.html', context)

def update_notebook(request,notebook_title):
    if not request.user.is_authenticated():
        return render(request, 'wowCS/login.html')

    instance = get_object_or_404(Notebook, notebook_title=notebook_title)
    form = NoteBookForm(request.POST or None, request.FILES or None, instance=instance)
    if instance.user!=request.user:
        return render(request, 'wowCS/wrong.html', {'error_message': "<h1>You can't update that notebook!</h1>"})
    # the form is valid when the method is POST and files exist.
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        "title": instance.notebook_title,
        "instance": instance,
        "form":form,
    }

    # for the get method
    return render(request, "wowCS/notebook_form.html", context)

def delete_notebook(request, notebook_title):
    if not request.user.is_authenticated():

mysite/wowCS/templates/wowCS/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Marknote, a place for sharing markdown notes.">
    <meta name="author" content="Diyi and Xueguang">
    <title>{% block title %}Marknote{% endblock %}</title>
    {% load staticfiles %}
    <!--link data-require="bootstrap-css@3.1.1" data-semver="3.1.1" rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" /-->
    <!-- Bootstrap Core CSS -->
    <link type="text/css" rel="stylesheet" href="/static/css/bootstrap.min.css">
    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="/static/css/style.css"/>
    <!--script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css"-->

{% block extend-header %}

{% endblock %}
</head>


<body>
    {% block navbar %}
    {% endblock %}

    <div class="bd-pageheader" id='bd-pageheader'>
        <div class="container">
            <h1>Welcome</h1>
            <p class="lead">This is Marknote, a place for markdown blogs, where sharing and viewing complex thoughts made easily.</p>
        </div>
    </div>
    <div class="main-container container">
        <div class="row">

            <div class="col-md-8">
            {% block body %}

            {% endblock %}
            </div>

            {% block sidebar %}
              {% include 'wowCS/sidebar.html'%}
            {% endblock %}

            {% block footer %}
              {% include 'wowCS/footer.html' %}
            {% endblock %}
        </div>
    </div>


    <div id="modal-from-dom" class="modal hide fade">
        <div class="modal-header">
            <a href="#" class="close">&times;</a>
             <h3>Delete Note</h3>
        </div>
        <div class="modal-body">
            <p>You are about to delete your note, this procedure is irreversible.</p>
            <p>Do you want to proceed?</p>
            <p id="debug-url"></p>
        </div>
        <div class="modal-footer">
            <a href="delete.php?ref=" class="btn danger">Yes</a>
            <!-- <a href="delete.php?some=param&ref=" class="btn danger">Yes 2</a> -->
            <a href="#" data-dismiss="modal" class="btn secondary">No</a>
        </div>
    </div>
    <!--script data-require="jquery@*" data-semver="2.0.3" src="http://code.jquery.com/jquery-2.0.3.min.js"></script>
    <script data-require="bootstrap@*" data-semver="3.1.1" src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script-->
    <script src="/static/js/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/main.js"></script>
</body>

</html>

mysite/wowCS/templates/wowCS/catalogue.html
{% extends 'wowCS/base.html' %}
{% block navbar %}
{% include 'wowCS/navbar.html' with islogin=True %}
{% endblock %}
{% block title %}Notebook Catalogue{% endblock %}
{% block body %}

    <h1>{{ notebook.notebook_title }}</h1>
    <h3>{{ notebook.notebook_description }}</h3>
      <div class="btn-toolbar" role="toolbar">
        <div class="btn-group btn-group-lg btn-group-justified btn-group-fill-height">

          {% for note in notebook.note_set.all %}
          <a class="btn btn-default" role="button" onclick='window.location="{% url 'wowCS:note-update' note.id %}"'>
            {{note.note_title}}
            <span class="pull-right">
              <span class="btn btn-xs btn-default" href='{% url 'wowCS:note-update' note.id %}'>
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
              </span>
              <span class="btn btn-xs btn-default">
                <span class="glyphicon glyphicon-trash"  data-record-title="{{note.note_title}}"
                      data-toggle="modal" id="confirm-delete" data-record-id="{{note.id}}"
                      aria-hidden="true" noteid="{{note.id}}"></span>
              </span>
            </span>
          </a>
          {% endfor %}
        </div>
      </div>




    

    <div class="col-sm-12">
        <br>
        <a href="{% url 'wowCS:note-add' %}">
            <button type="button" class="btn btn-success">
                <span class="glyphicon glyphicon-plus"></span>&nbsp; Add a Note
            </button>
        </a>
    </div>

    {% if error_message %}

        <p><strong>{{ error_message }}</strong></p>

    {% endif %}


{% endblock %}

{% block sidebar %}

{% include 'wowCS/sidebar.html' %}

{% endblock %}

mysite/wowCS/templates/wowCS/create_notebook.html
{% extends 'wowCS/base.html' %}
{% block title %}Add a New Notebook{% endblock %}


{% block navbar %}

{% include 'wowCS/navbar.html' with islogin=True %}

{% endblock %}

{% block body %}


{#<div class="container-fluid">#}
{##}
{#    <div class="row">#}
{##}
{#        <div class="col-sm-12 col-md-7">#}
{#            <div class="panel panel-default">#}
{#                <div class="panel-body">#}
                    <h3>Add a New Notebook</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <p>Only Numbers and English Letters are allowed in notebook_title</p>
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'wowCS/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
{#                </div>#}
{#            </div>#}
{#        </div>#}
{##}
{#    </div>#}
{##}
{#</div>#}
{% endblock %}

{% block sidebar %}

{% include 'wowCS/sidebar.html' %}

{% endblock %}

mysite/wowCS/templates/wowCS/detail.html
{% extends 'wowCS/base.html' %}

{% block navbar %}

{% include 'wowCS/navbar.html' with islogin=islogin %}

{% endblock %}

{% block body %}
<h3>{{note.note_title}}</h3>
<p class='created-time'>Created at {{ note.date }}</p>
{{ note_content|safe }}

{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}

<div class="buttom-options">
  {% if is_favorite %}
  <a class="btn  btn--icon  btn--favorite" noteid="{{ note.id }}" href=#><i>{{ note.favorite_count }}</i><span>Favorite</span></a>
  {% else %}
  <a class="btn  btn--icon  btn--default" noteid="{{ note.id }}" href=#><i>{{ note.favorite_count }}</i><span>Favorite</span></a>
  {% endif %}
</div>
{% endblock %}
{% block sidebar %}

{% include 'wowCS/sidebar.html' %}

{% endblock %}

mysite/wowCS/templates/wowCS/footer.html
<footer class="col-md-4">
  <div>
    <p>&copy; Diyi and Xueguang 2017</p>
  </div>
</footer>

mysite/wowCS/templates/wowCS/form-template.html
{% for field in form %}

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>

        <label class="control-label col-sm-2">{{ field.label_tag }}</label>

        <div class="col-sm-10">{{ field }}</div>
    </div>

{% endfor %}

mysite/wowCS/templates/wowCS/index.html
{% extends 'wowCS/base.html'  %}

{% block navbar %}
  {% include 'wowCS/navbar.html' with islogin=islogin %}
{% endblock %}


{% block body %}

{% if all_note %}
  <h1 class="page-header">
    Public Notes
    <small>Most Favorited</small>
  </h1>

  {% for note in all_note %}
    <h2>
      <a onclick='window.location="{% url 'wowCS:detail' note.id %}"'>
        {{note.note_title}}
      </a>
    </h2>
    <p class="lead">
      by <a href="#">{{ note.user }}</a>
    </p>
    <p><span class="glyphicon glyphicon-time"></span> Posted on {{ note.date }}</p>
    <p>preview-api placeholder</p>
    <a  href="#" class="btn btn-primary" onclick='window.location="{% url 'wowCS:detail' note.id %}"'>
      Read More <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
  {% endfor %}

{% else %}
  <h3> No Notes!</h3>
{% endif %}

{% endblock %}

mysite/wowCS/templates/wowCS/login.html
{% extends 'wowCS/base.html' %}
{% block title %}Login{% endblock %}

{% block navbar %}
  {% include 'wowCS/navbar.html' with islogin=False %}
{% endblock %}

{% block body %}

                    <h3>Log In</h3>
                    {% if error_message %}
                        <p class="error-message"><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'wowCS:login'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>

                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'wowCS:register' %}">Click here</a> to register.
                </div>

{% endblock %}

mysite/wowCS/templates/wowCS/note_form.html
{% extends "wowCS/base.html" %}

{% block extend-header %}

{{form.media}}
{% endblock %}
{% block navbar %}

{% include 'wowCS/navbar.html' with islogin=True %}

{% endblock %}
{% block body %}
<div class="container">
  <div class="row">
    <div class="col-md-12">

  <form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
    {{ form.as_p }}
    <input type='submit' class='btn btn-default' value='Create Post' />
  </form>
</div></div></div>
{% endblock body %}

{% block sidebar %}

{% include 'wowCS/sidebar.html' %}

{% endblock %}

mysite/wowCS/templates/wowCS/notebook_form.html
{% extends "wowCS/base.html" %}

{% block navbar %}

{% include 'wowCS/navbar.html' with islogin=True %}

{% endblock %}
{% block body %}
<div class='col-sm-6 col-sm-offset-3'>
<h1>Update The Notebook</h1>

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form.as_p }}
<input type='submit' class='btn btn-default' value='Create Post' />
</form>
</div>
{% endblock body %}

{% block sidebar %}

{% include 'wowCS/sidebar.html' %}

{% endblock %}

mysite/wowCS/templates/wowCS/profile.html
{% extends 'wowCS/base.html' %}
{% block title %}Profile{% endblock %}

{% block navbar %}
{% include 'wowCS/navbar.html' with islogin=True %}
{% endblock %}

{% block body %}


    {{ user.username }}

    {% if error_message %}

        <p><strong>{{ error_message }}</strong></p>

    {% endif %}


{% endblock %}

{% block sidebar %}

{% include 'wowCS/sidebar.html' %}

{% endblock %}

mysite/wowCS/templates/wowCS/show_all_notebooks.html
{% extends 'wowCS/base.html' %}

{% block navbar %}
{% include 'wowCS/navbar.html' with islogin=True %}
{% endblock %}

{% block body %}
    {% if all_notebooks %}

        <h3> My notebooks:</h3>
        <div class="list-group">
            {% for notebook in all_notebooks %}
              <a  class="list-group-item"
                  href = '{% url 'wowCS:catalogue' notebook.notebook_title %}'>{{notebook.notebook_title}}
              </a>
            {% endfor %}
        </div>

    {% else %}

        <h3> You don't have any notebook yet.</h3>

    {% endif %}

{% endblock %}

{% block sidebar %}

{% include 'wowCS/sidebar.html' %}

{% endblock %}

mysite/wowCS/templates/wowCS/show_all_notes.html
{% extends 'wowCS/base.html' %}

{% block navbar %}
{% include 'wowCS/navbar.html' with islogin=True %}
{% endblock %}

{% block body %}
{% if all_notes %}




<div class="container">
  <div class="row">
    <div class="col-md-12">
    <h1 class="page-header">
        All My Notes
        <small>Most Recent</small>
    </h1>

        {% for note in all_notes %}

        <h2>
            <a href="#" onclick='window.location="{% url 'wowCS:detail' note.id %}"'>
              {{note.note_title}}
            </a>
        </h2>
        <p class="lead">
            by <a href="#">preview-username-placeholder</a>
        </p>
        <p><span class="glyphicon glyphicon-time"></span> Posted on preview-time-placeholder</p>
        <p> preview-api placeholder preview-api placeholder preview-api placeholder preview-api placeholder preview-api placeholder</p>
        <a class="btn btn-primary"  href="#" onclick='window.location="{% url 'wowCS:detail' note.id %}"'>
          Read <span class="glyphicon glyphicon-chevron-right"></span></a>
        <a class="btn btn-primary"  href="#" onclick='window.location="{% url 'wowCS:note-update' note.id %}"'>
          <span class="glyphicon glyphicon-pencil"></span> Edit / Delete </a>

        <hr>
        {% endfor %}

  </div>

  </div>
</div>


{% else %}

<h3> You don't have any note yet.</h3>

{% endif %}

{% endblock %}

{% block sidebar %}

{% include 'wowCS/sidebar.html' %}

{% endblock %}

mysite/wowCS/templates/wowCS/wrong.html
{% extends 'wowCS/base.html' %}
{% block title %}Permission Denied{% endblock %}

{% block navbar %}
{% include 'wowCS/navbar.html' with islogin=islogin %}
{% endblock %}

{% block body %}


    <p><strong>{{ error_message|safe }}</strong></p>


{% endblock %}

{% block sidebar %}

{% include 'wowCS/sidebar.html' %}

{% endblock %}